---
version: "3.9"

services:
  postgres:
    container_name: "postgres"
    image: "postgres:alpine"
    restart: "always"
    environment:
      - "POSTGRES_USER"
      - "POSTGRES_PASSWORD"
      - "POSTGRES_DB"
    volumes:
      - "./docker/init-postgres.sh:/docker-entrypoint-initdb.d/init-postgres.sh"
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: "Dockerfile"
    command: "corepack pnpm dev"
    environment:
      PORT: "${PORT}"
      REFRESH_COUNT: "0"
      JWT_ACCESS_EXPIRES: "${JWT_ACCESS_EXPIRES}"
      JWT_REFRESH_EXPIRES: "${JWT_REFRESH_EXPIRES}"
      JWT_ACCESS_SECRET_FILE: "/run/secrets/jwt_access_secret"
      JWT_REFRESH_SECRET_FILE: "/run/secrets/jwt_refresh_secret"
      JWT_INTERNAL_SECRET_FILE: "/run/secrets/jwt_internal_secret"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - "./src:/srv/api/src"
      - "./tsconfig.json:/srv/api/tsconfig.json"
      - "./tsup.config.ts:/srv/api/tsup.config.ts"
    secrets:
      - "jwt_access_secret"
      - "jwt_refresh_secret"
      - "jwt_internal_secret"

secrets:
  jwt_access_secret:
    file: ".jwt_access_secret"
  jwt_refresh_secret:
    file: ".jwt_refresh_secret"
  jwt_internal_secret:
    file: ".jwt_internal_secret"
