/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
	const AUTHENTICATION_STATUS: typeof import("./src/utilities/constants")["AUTHENTICATION_STATUS"];
	const HTTPError: typeof import("./src/utilities/errors")["HTTPError"];
	const Resources: typeof import("./src/utilities/resources")["Resources"];
	const STORAGE_KEYS: typeof import("./src/utilities/constants")["STORAGE_KEYS"];
	const createRef: typeof import("react")["createRef"];
	const forwardRef: typeof import("react")["forwardRef"];
	const joinClasses: typeof import("./src/utilities/joinClasses")["joinClasses"];
	const lazy: typeof import("react")["lazy"];
	const memo: typeof import("react")["memo"];
	const startTransition: typeof import("react")["startTransition"];
	const useCallback: typeof import("react")["useCallback"];
	const useContext: typeof import("react")["useContext"];
	const useDebugValue: typeof import("react")["useDebugValue"];
	const useDeferredValue: typeof import("react")["useDeferredValue"];
	const useEffect: typeof import("react")["useEffect"];
	const useId: typeof import("react")["useId"];
	const useImperativeHandle: typeof import("react")["useImperativeHandle"];
	const useInsertionEffect: typeof import("react")["useInsertionEffect"];
	const useLayoutEffect: typeof import("react")["useLayoutEffect"];
	const useMemo: typeof import("react")["useMemo"];
	const useReducer: typeof import("react")["useReducer"];
	const useRef: typeof import("react")["useRef"];
	const useState: typeof import("react")["useState"];
	const useSyncExternalStore: typeof import("react")["useSyncExternalStore"];
	const useTransition: typeof import("react")["useTransition"];
}
