/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-auto-import
export {}
declare global {
	const AUTHENTICATION_STATUS: typeof import("./src/utilities/constants")["AUTHENTICATION_STATUS"];
	const AUTHORIZATION_REDUCER_TYPES: typeof import("./src/utilities/constants")["AUTHORIZATION_REDUCER_TYPES"];
	const ArticleContext: typeof import("./src/context/Article/index")["ArticleContext"];
	const ArticleProvider: typeof import("./src/context/Article/index")["ArticleProvider"];
	const AuthContext: typeof import("./src/context/Auth/index")["AuthContext"];
	const AuthProvider: typeof import("./src/context/Auth/index")["AuthProvider"];
	const BRAND_NAME: typeof import("./src/utilities/constants")["BRAND_NAME"];
	const CommentContext: typeof import("./src/context/Comment/index")["CommentContext"];
	const CommentProvider: typeof import("./src/context/Comment/index")["CommentProvider"];
	const Context: typeof import("./src/context/index")["Context"];
	const EMAIL_REGEX: typeof import("./src/utilities/constants")["EMAIL_REGEX"];
	const HTTPError: typeof import("./src/utilities/errors")["HTTPError"];
	const QUERY_KEYS: typeof import("./src/utilities/constants")["QUERY_KEYS"];
	const Resources: typeof import("./src/utilities/resources")["Resources"];
	const STORAGE_KEYS: typeof import("./src/utilities/constants")["STORAGE_KEYS"];
	const UserContext: typeof import("./src/context/User/index")["UserContext"];
	const UserProvider: typeof import("./src/context/User/index")["UserProvider"];
	const afterAll: typeof import("vitest")["afterAll"];
	const afterEach: typeof import("vitest")["afterEach"];
	const assert: typeof import("vitest")["assert"];
	const beforeAll: typeof import("vitest")["beforeAll"];
	const beforeEach: typeof import("vitest")["beforeEach"];
	const chai: typeof import("vitest")["chai"];
	const createRef: typeof import("react")["createRef"];
	const describe: typeof import("vitest")["describe"];
	const expect: typeof import("vitest")["expect"];
	const forwardRef: typeof import("react")["forwardRef"];
	const it: typeof import("vitest")["it"];
	const joinClasses: typeof import("./src/utilities/joinClasses")["joinClasses"];
	const lazy: typeof import("react")["lazy"];
	const memo: typeof import("react")["memo"];
	const startTransition: typeof import("react")["startTransition"];
	const suite: typeof import("vitest")["suite"];
	const test: typeof import("vitest")["test"];
	const useCallback: typeof import("react")["useCallback"];
	const useContext: typeof import("react")["useContext"];
	const useDebugValue: typeof import("react")["useDebugValue"];
	const useDeferredValue: typeof import("react")["useDeferredValue"];
	const useEffect: typeof import("react")["useEffect"];
	const useId: typeof import("react")["useId"];
	const useImperativeHandle: typeof import("react")["useImperativeHandle"];
	const useInsertionEffect: typeof import("react")["useInsertionEffect"];
	const useLayoutEffect: typeof import("react")["useLayoutEffect"];
	const useMemo: typeof import("react")["useMemo"];
	const useReducer: typeof import("react")["useReducer"];
	const useRef: typeof import("react")["useRef"];
	const useState: typeof import("react")["useState"];
	const useSyncExternalStore: typeof import("react")["useSyncExternalStore"];
	const useTransition: typeof import("react")["useTransition"];
	const vi: typeof import("vitest")["vi"];
	const vitest: typeof import("vitest")["vitest"];
}
