#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE TABLE IF NOT EXISTS USERS(
		uuid UUID NOT NULL UNIQUE PRIMARY KEY,
		username VARCHAR(20) NOT NULL UNIQUE,
		email VARCHAR(320) NOT NULL UNIQUE,
		password VARCHAR(80) NOT NULL UNIQUE,
		bio TEXT,
		image VARCHAR(2048)
	);

	CREATE TABLE IF NOT EXISTS USERS_FOLLOWS(
		origin UUID NOT NULL,
		destination UUID NOT NULL,
		isActive BOOLEAN NOT NULL,
		FOREIGN KEY (origin)
			REFERENCES USERS(uuid),
		FOREIGN KEY(destination)
			REFERENCES USERS(uuid),
		UNIQUE(origin, destination)
	);

	CREATE TABLE IF NOT EXISTS ARTICLES(
		ulid UUID NOT NULL UNIQUE PRIMARY KEY,
		slug VARCHAR(200) NOT NULL UNIQUE,
		title VARCHAR(200) NOT NULL UNIQUE,
		description VARCHAR(400) NOT NULL,
		body TEXT NOT NULL,
		created_at BIGINT NOT NULL,
		updated_at BIGINT NOT NULL,
		author UUID NOT NULL,
		FOREIGN KEY(author)
			REFERENCES USERS(uuid)
	);

	CREATE TABLE IF NOT EXISTS ARTICLE_FAVORITES(
		ulid UUID NOT NULL UNIQUE PRIMARY KEY,
		article UUID NOT NULL,
		favoritedBy UUID NOT NULL,
		isActive BOOLEAN NOT NULL,
		FOREIGN KEY(article)
			REFERENCES ARTICLES(ulid),
		FOREIGN KEY(favoritedBy)
			REFERENCES USERS(uuid),
		UNIQUE(article, favoritedBy)
	);

	CREATE TABLE IF NOT EXISTS COMMENTS(
		ulid UUID NOT NULL UNIQUE PRIMARY KEY,
		author UUID NOT NULL,
		article UUID NOT NULL,
		body TEXT NOT NULL,
		created_at BIGINT NOT NULL,
		updated_at BIGINT NOT NULL,
		FOREIGN KEY(author)
			REFERENCES USERS(uuid),
		FOREIGN KEY(author)
			REFERENCES ARTICLES(ulid)
	);

	CREATE TABLE IF NOT EXISTS TAGS(
		ulid UUID NOT NULL UNIQUE PRIMARY KEY,
		tag VARCHAR(20) NOT NULL,
		article UUID NOT NULL UNIQUE,
		FOREIGN KEY(article)
			REFERENCES ARTICLES(ulid)
	);

	\d USERS
	\d USERS_FOLLOWS
	\d ARTICLES
	\d ARTICLE_FAVORITES
	\d COMMENTS
	\d TAGS
EOSQL
