#!/bin/sh
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE TABLE IF NOT EXISTS USERS(
		uuid UUID NOT NULL UNIQUE PRIMARY KEY,
		username VARCHAR(20) NOT NULL UNIQUE,
		email VARCHAR(320) NOT NULL UNIQUE,
		password VARCHAR(80) NOT NULL UNIQUE,
		bio TEXT,
		image VARCHAR(2048)
	);

	CREATE TABLE IF NOT EXISTS USERS_FOLLOWS(
		origin UUID NOT NULL,
		destination UUID NOT NULL,
		isActive BOOLEAN NOT NULL,
		FOREIGN KEY (origin)
			REFERENCES USERS(uuid),
		FOREIGN KEY(destination)
			REFERENCES USERS(uuid),
		UNIQUE(origin, destination)
	);

	\d USERS
	\d USERS_FOLLOWS
EOSQL
