---
version: "3.9"

services:
  nginx:
    container_name: "backend-nmongo-nginx"
    image: "nginx:alpine"
    depends_on:
      - "api"
    ports:
      - "${PORT}:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
  api:
    container_name: "backend-nmongo-api"
    build:
      context: .
      dockerfile: "Dockerfile"
    command: "corepack pnpm dev"
    environment:
      PORT: "80"
      REFRESH_COUNT: "0"
      JWT_ACCESS_EXPIRES: "${JWT_ACCESS_EXPIRES}"
      JWT_REFRESH_EXPIRES: "${JWT_REFRESH_EXPIRES}"
      JWT_ACCESS_SECRET_FILE: "/run/secrets/jwt_access_secret"
      JWT_REFRESH_SECRET_FILE: "/run/secrets/jwt_refresh_secret"
      JWT_INTERNAL_SECRET_FILE: "/run/secrets/jwt_internal_secret"
    volumes:
      - "./src:/srv/api/src"
      - "./tsconfig.json:/srv/api/tsconfig.json"
      - "./tsup.config.ts:/srv/api/tsup.config.ts"
    secrets:
      - "jwt_access_secret"
      - "jwt_refresh_secret"
      - "jwt_internal_secret"
    depends_on:
      - "mongo"
  mongo:
    container_name: "backend-nmongo-mongo"
    image: "mongo:latest"
    restart: "always"

secrets:
  jwt_access_secret:
    file: ".jwt_access_secret"
  jwt_refresh_secret:
    file: ".jwt_refresh_secret"
  jwt_internal_secret:
    file: ".jwt_internal_secret"
